### PR TITLE
Added Chatter & Connect REST API Requests

### PR DESCRIPTION
**Pull request by mhgoldfarb**
Added 27 request templates for the Chatter & Connect REST APIs

### CODE REVIEW

**Review by scolladon — APPROVED** [review]
PR Checked ok
Value is great! Thanks @mhgoldfarb!

**Comment by pozil** [comment]
Yes, thanks for that great contribution @mhgoldfarb.

@scolladon I'm on holiday this week so I can't do extensive testing before Sept 2 but I trust your judgement so feel free to merge that before if you don't want to wait.

**Review by scolladon — APPROVED** [review]
@pozil On my point of view it can wait next week for your valuable eyes :)

**Review by pozil — APPROVED** [review]
I'm done with the review and testing.
Awesome job @mhgoldfarb!

**Comment by mhgoldfarb** [comment]
Thank you so much @pozil @scolladon for not only for reviewing and accepting my work, but also for establishing and maintaining this incredible project. I am looking forward to contributing more in the future!

**Pull request merged**
