### PR TITLE
Adding query explain callout

### PR DESCRIPTION
**Pull request by henriqueadonai**
Use the Query resource along with the explain parameter to get feedback on how Salesforce executes your query, report, or list view.

### CODE REVIEW

**Comment by henriqueadonai** [comment]
Use the Query resource along with the explain parameter to get feedback on how Salesforce executes your query, report, or list view.

**Comment by henriqueadonai** [comment]
Use the Query resource along with the explain parameter to get feedback on how Salesforce executes your query, report, or list view.

**Comment by scolladon** [comment]
Hi @henriqueadonai 

Thanks for this PR.
I think what you want is to add the explain query paramater to the the https://github.com/scolladon/postman-salesforce-apis/blob/master/src/collections/salesforce_apis/rest/query.json endpoint right ?

Seb

**Comment by henriqueadonai** [comment]
Hi @scolladon  thanks for considering my PR.
I thought would be interesting to add an extra callout in the query [](https://github.com/scolladon/postman-salesforce-apis/blob/master/src/collections/salesforce_apis/rest/query.json 
)
that has the parameter explain to check query performance.

**Comment by scolladon** [comment]
I prefer to keep the existing query endpoint and just add the new parameter (the same way it is done for the queryAll). Could you apply the queryAll way to deal with the explain parameter to the query endpoint ?

**Comment by henriqueadonai** [comment]
Yes, I'm going to change to queryAll as a parameter

**Pull request closed without merging**
